name: Update Data

on:
  schedule:
    - cron: '8 17 * * *'  # This runs the workflow every day at 5:08 PM UTC (12:08 PM EST)
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance

      - name: Run generate_data.py
        run: |
          python generate_data.py

      - name: Print repository URL for debugging
        run: echo "Repository URL: https://${{ secrets.PAT3 }}@github.com/dylanleclair19/mptesting.git"
      
      - name: Commit and push changes
        env:
          PAT3: ${{ secrets.PAT3 }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://${{ secrets.PAT3 }}@github.com/dylanleclair19/mptesting.git
          git remote -v
          git add data1.json
          git commit -m 'Automated data update'
          git push https://${{ secrets.PAT3 }}@github.com/dylanleclair19/mptesting.git HEAD:main
